# Generated by Django 4.2.23 on 2025-07-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_notification_adminreport_reviewinteraction'),
        ('products', '0005_review_helpful_votes_review_unhelpful_votes_and_more'),
    ]

    operations = [
    ]
